### ISSUE TITLE
assert doesn't match

### ISSUE THREAD

**Issue by ymadh** [martin-helmich/phpunit-json-assert#21]
Is it possible to check for false tests?  something along the lines of assertNotEquals or assertNotContains?

**Comment by martin-helmich** [comment]
Sure! Simply use [`logicalNot(...)`](https://api.phpunit.de/classes/PHPUnit_Framework_Assert/logicalNot.html) as wrapper:

```php
assertThat($jsonDocument, logicalNot(containsJsonValue('$.foo', 'bar')));
```
