### ISSUE TITLE
Properties

### ISSUE THREAD

**Issue by prinzplanloser** [martin-helmich/phpunit-json-assert#22]
How can I check attached properties?

**Comment by martin-helmich** [comment]
What exactly do you mean? Can you provide an example of what you want to achieve?

**Comment by prinzplanloser** [comment]
i need to check   
{
    "data": {
        "id": 8,
        "title": "Quas qui dicta quae quia sunt."

asserts work on (data) but do not work on id, title

**Comment by prinzplanloser** [comment]
$schema = [
            'properties' => [
                'data' => ['type' => 'object'],
                'id'=>['type'=>'string'],
            ]];
        $this->assertJsonDocumentMatchesSchema($content, $schema);

I specifically made a mistake in the id scheme, but the test passes

**Comment by prinzplanloser** [comment]
I found my mistake,i needed to do this 
$schema = [
            'properties' => [
                'data' => ['type' => 'object',
                    'properties' => [
                        'id' => ['type' => 'integer'],
                        'title' => ['type' => 'string']
                    ]],
            ]];
