### ISSUE TITLE
Arrays

### ISSUE THREAD

**Issue by prinzplanloser** [martin-helmich/phpunit-json-assert#23]
Hi my json looks like this

{
    "data": [
        {
            "id": 55,

How can I correctly describe the scheme so that the asserts works? im need
assertJsonDocumentMatchesSchema method. 

[
            'type' => 'object',
            'properties' => [
                'data' => ['type' => 'array',properties=>[
                                'id'=>['type'=>'int']]]
This approach does not work

**Comment by martin-helmich** [comment]
This is nothing special or exclusive to this library -- it just uses JSON schemas as described by the official JSON schema specification. Please have a look at the [official JSON schema docs](https://json-schema.org/) for more information.

In your case, it'd probably be

```
'data' => [
  'type' => 'array',
  'items' => [
    'properties' => [...]
  ]
]
```
