### ISSUE TITLE
Release 3.4.0

### ISSUE THREAD

**Issue by martinssipenko** [martin-helmich/phpunit-json-assert#39]
Hi @martin-helmich, could you please do a release of [these changes](https://github.com/martin-helmich/phpunit-json-assert/compare/v3.3.0...master) so we can afterwards update https://github.com/martin-helmich/phpunit-psr7-assert to use `martin-helmich/phpunit-json-assert:^3.4`?

**Comment by martin-helmich** [comment]
:+1: Done! Thanks for the reminder. https://github.com/martin-helmich/phpunit-json-assert/releases/tag/v3.4.0

**Comment by martin-helmich** [comment]
BTW, https://github.com/martin-helmich/phpunit-psr7-assert has dependabot enabled, so dependencies over there should update automatically.

**Comment by martinssipenko** [comment]
Any way you could trigger it there and do a release afterward?
